### ISSUE TITLE
No HTTP status code information returned if response body is empty

### ISSUE THREAD

**Issue by ashmrtn** [microsoft/kiota-http-go#151]
My team and I have discovered some resources that take too long to return data for certain page sizes. These resources consistently result in 503 errors with no body content being sent back. The retries in the default graph client don't get us passed the 503s either. When using the `kiota-serialization-json-go` library and other graph SDK libraries to communicate with the Graph servers we only get an [error](https://github.com/microsoft/kiota-serialization-json-go/blob/a13c7c50383789df375fb0438590dc83aea754a8/json_parse_node.go#L29) of "content is empty" back from graph SDK in these situations

This is problematic because we lose information about the HTTP status code. For example, we've found that if we see consistent 503s with no content returned we can reduce the requested page size to make progress. This strategy would probably not make sense if the status code was a 4xx error though

Would it be possible to update the graph SDK (I'm unsure which repo the update would be in) to somehow return the HTTP status code? We've worked around the issue for the moment by adding our own middleware to the graph client and explicitly checking for no content and returning an error, but that feels a bit heavy handed

As an additional note, depending on which graph SDK repo the fix is made in, other repos may need updating as well. For example, all the serialization libraries contain the line `errors.New("content is empty")` like I linked above

**Comment by baywet** [comment]
Sorry, I got confused with another issue for a moment, transferred this issue again.
[Here is the problematic line in go](https://github.com/microsoft/kiota-http-go/blob/14969249eb4682a669cababeccf03ca4aeed00ab/nethttp_request_adapter.go#L714)

**Comment by ashmrtn** [comment]
No worries, keeping everything in order between the different repos is certainly a task in itself. Thanks for moving the issue to the proper place

Unfortunately, I don't have the time right now to get a PR up for this. Looking a the golang library, it seems like a few more changes beyond the empty content check would be required since just returning `nil` without an error from `getRootParseNode` would [result](https://github.com/microsoft/kiota-http-go/blob/14969249eb4682a669cababeccf03ca4aeed00ab/nethttp_request_adapter.go#L354) in the caller ultimately getting back no `Parsable` and no error

Ideally the caller should get back something that allows inspecting the HTTP status code. I don't believe `kiota-http-go` really has the framework to handle that at the moment since it relies on parsing odata errors sent back as response body content

**Comment by ashmrtn** [comment]
see #152

**Comment by baywet** [comment]
Hi @ashmrtn
Is this still something you're looking to fix with a pull request?

**Comment by ashmrtn** [comment]
ah, sorry, this sort of fell off my radar. I think it was fixed by #152 and can be closed?

**Comment by baywet** [comment]
It does, sorry, I go confused reviewing a bunch of issues. I think we forgot to close this issue here, closing.
