### ISSUE TITLE
ShouldRetry of Retry Handler Option should allow other response status code

### ISSUE THREAD

**Issue by ritu-rubrik** [microsoft/kiota-http-go#175]
Hello,
I am trying to over ride the retry condition for Retry handler by setting the ShouldRetry function to retrun true for certain response  status code. However in the middle ware code the GetShouldRetry is considered only if the **middleware.isRetriableErrorCode(resp.StatusCode)**  returns true since this is && condition. Does this mean we can only attempt retry for the 3 response status code mentioned here.
```go

func (middleware RetryHandler) retryRequest(ctx context.Context, pipeline Pipeline, middlewareIndex int, options retryHandlerOptionsInt, req *nethttp.Request, resp *nethttp.Response, executionCount int, cumulativeDelay time.Duration, observabilityName string) (*nethttp.Response, error) {
	if middleware.isRetriableErrorCode(resp.StatusCode) &&
		middleware.isRetriableRequest(req) &&
		executionCount < options.GetMaxRetries() &&
		cumulativeDelay < time.Duration(absoluteMaxDelaySeconds)*time.Second &&
		options.GetShouldRetry()(cumulativeDelay, executionCount, req, resp) {
		executionCount++
		delay := middleware.getRetryDelay(req, resp, options, executionCount)
		cumulativeDelay += delay
		req.Header.Set(retryAttemptHeader, strconv.Itoa(executionCount))
		if req.Body != nil {
			s, ok := req.Body.(io.Seeker)
			if ok {
				s.Seek(0, io.SeekStart)
			}
		}
		if observabilityName != "" {
			ctx, span := otel.GetTracerProvider().Tracer(observabilityName).Start(ctx, "RetryHandler_Intercept - attempt "+fmt.Sprint(executionCount))
			span.SetAttributes(attribute.Int("http.retry_count", executionCount),
				attribute.Int("http.status_code", resp.StatusCode),
			)
			defer span.End()
			req = req.WithContext(ctx)
		}
		t := time.NewTimer(delay)
		select {
		case <-ctx.Done():
			// Return without retrying if the context was cancelled.
			return nil, ctx.Err()

			// Leaving this case empty causes it to exit the switch-block.
		case <-t.C:
		}
		response, err := pipeline.Next(req, middlewareIndex)
		if err != nil {
			return response, err
		}
		return middleware.retryRequest(ctx, pipeline, middlewareIndex, options, req, response, executionCount, cumulativeDelay, observabilityName)
	}
	return resp, nil
}
```

**Comment by baywet** [comment]
Hi @ritu-rubrik ,
Thanks for using kiota and for reaching out.
Yes, the default retry handler implementation will only retry for the following status codes:
- 429
- 503
- 504
https://github.com/microsoft/kiota-http-go/blob/ab72ea5a6539adc5a6dd2516cf5726fe8724cbd2/retry_handler.go#L170

Which codes do you believe are missing?

**Comment by ritu-rubrik** [comment]
What if I want to customize this by retrying for a particular response status code such as 500.
Or maybe even for an error message?

**Comment by ritu-rubrik** [comment]
I guess I can set it in the ShouldRetry function but still it will not be honoured becuase if the first if condition in the above code.
I dont understand how can we utilise ShouldRetry to override the default status code.

**Comment by baywet** [comment]
Thanks for the additional context.
The reason why we settled on hard-coding these status codes is because they are the only ones that map to transient errors and that are safe to retry (no-double submission issues etc...)
How would you guarantee that retrying a 500 doesn't end up creating an additional entry in the case of a POST for example?

**Comment by ritu-rubrik** [comment]
I have a related question on setting retry Options for per api request. I am doing it as follows:

```
	configuration := serviceprincipals.
		ServicePrincipalsRequestBuilderPostRequestConfiguration{}

		retryOption := nethttplibrary.RetryHandlerOptions{
		ShouldRetry:  nil,
		MaxRetries:   5,
		DelaySeconds: 2,
	}
			configuration.Options = append(
				configuration.Options,
				retryOption,
			)

	servicePrincipal, err := client.ServicePrincipals().Post(
		ctx,
		requestBody,
		&configuration,
	)
```
Would this ensure that the retry options will be injected for this request and also, will it will override any RetryHandlerOptions set at the client level?

**Comment by baywet** [comment]
> So Can I assume this is a directive/restriction from Microsoft end that no other status codes/errors than the above listed should be retried?

This is the safest stance not knowing the implementation details of the API itself. And part of the reason why an API is sitting between the clients and the service is so the clients do not need to know about implementation details.

> Also, here you are only allowing retry for POST/PATCH/PUT and not for GET or DELETE is this also intentional

Can you provide more information on where you're getting this information please? The design is to retry any request as long as the status code is a transient error AND (there is no request body OR the request body can be replayed). But we don't exclude any request verb from the logic here.

> GET a value and the service is unavailable, it is desirable to retry a few times?

GET requests are supposed to be idempotent, so they it's supposed to be ok to retry them. Some APIs might have made different implementation choices, but if that's the case, it's not following REST standard practices.

> Would this ensure that the retry options will be injected for this request and also, will it will override any RetryHandlerOptions set at the client level?

At glance, it looks correct.

**Comment by ritu-rubrik** [comment]
@baywet My bad I mis read the below code and though only POST PUT and PATCH are considered.
```
func (middleware RetryHandler) isRetriableRequest(req *nethttp.Request) bool {
	isBodiedMethod := req.Method == "POST" || req.Method == "PUT" || req.Method == "PATCH"
	if isBodiedMethod && req.Body != nil {
		return req.ContentLength != -1
	}
	return true
}
```

if i set ShouldRetry to nil then will the retry happen?

**Comment by baywet** [comment]
No, that's not going to change anything with the error codes. 
https://github.com/microsoft/kiota-http-go/blob/main/retry_handler.go#L129

The should retry callback can be used to narrow down the retry conditions, not expand those.

**Comment by baywet** [comment]
Your only options at this point would be to either implement your own retry handler or submit a pull request to make error codes configurable.

**Comment by baywet** [comment]
But again, I'm not sure this is a good idea to begin with. There's no guarantee that retrying other status codes might not have side effects.

**Comment by ritu-rubrik** [comment]
Got it.
If I dont implement shouldRetry func and just set that to nil, It would still retry the default error codes right 
429
503
504.
I just want to customize the retry count and delay.

**Comment by baywet** [comment]
For that, you can just pass in options to set those values either at the request level or when you assemble the request adapter before passing it to the client.
