### ISSUE TITLE
Body not compressed on retry

### ISSUE THREAD

**Issue by meain** [microsoft/kiota-http-go#183]
Currently the compression handler does not kick in for retries even though the header does have `Content-Encoding: gzip` in it. This causes retried requests to fail.

Here is a sample scenario which would cause the request to fail:

- Request: (POST with gzip header and gzipped body)
- Response: 429 (throttled due to some external reason)
- Retry: (POST with gzip header, but uncompressed body) <-- this fails on server
- Response: 400 Bad Request (Error: Invalid Data.)

Found when using [microsoftgraph/msgraph-sdk-go](https://github.com/microsoftgraph/msgraph-sdk-go) and POSTing a drive item.

**Comment by baywet** [comment]
Hi @meain 
Thank you for using kiota and for reaching out.

Is this something you'd like to submit a pull request for provided some guidance?

You could start by adding another unit test here that leverages both handlers, replies with a 429 on the first request, and check the body is compressed for both requests.

https://github.com/microsoft/kiota-http-go/blob/59b1f5f55ea11cb26ae8f1b6774bc1d41d7c43e4/compression_handler_test.go#L49

**Comment by meain** [comment]
Huh, I'm not yet sure what is going on. I did setup the test with both retry and compression middleware, but it was sometimes erroring out saying length is 0 and sometime with length of the uncompressed data.

```
http: ContentLength=770 with Body length 1635
http: ContentLength=770 with Body length 0
```


```go
func TestCompressionHandlerCompressesRequestBodyWithRetry(t *testing.T) {
	postBody, _ := json.Marshal(map[string]string{"name": `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.a line in section 1.10.32.
    `, "email": "Test@Test.com"})

	var compressedBody []byte
	var requestCount int
	testServer := httptest.NewServer(nethttp.HandlerFunc(func(res nethttp.ResponseWriter, req *nethttp.Request) {
		if requestCount == 0 {
			res.WriteHeader(http.StatusTooManyRequests)
			requestCount++
			return
		}

		compressedBody, _ = io.ReadAll(req.Body)
		fmt.Fprint(res, `{}`)
	}))
	defer testServer.Close()

	client := GetDefaultClient(NewRetryHandler(), NewCompressionHandler())
	_, err := client.Post(testServer.URL, "application/json", bytes.NewBuffer(postBody))

	assert.NotZero(t, len(compressedBody))
	assert.Greater(t, len(postBody), len(compressedBody))
	assert.Equal(t, requestCount, 1)
	assert.NoError(t, err)
}
```

**Comment by baywet** [comment]
Thank you for the additional information.

It might be an ordering thing. Does it also pass with this change?

```diff
-client := GetDefaultClient(NewRetryHandler(), NewCompressionHandler())
+client := GetDefaultClient(NewCompressionHandler(), NewRetryHandler())
```

Your version observation [would concur with the changes made](https://github.com/microsoft/kiota-http-go/compare/v1.3.1...v1.4.4) i.e. if we retry and then run the compression handler, the header is already going to be present.

The factory [adds the handlers sequentially](https://github.com/microsoft/kiota-http-go/blob/59b1f5f55ea11cb26ae8f1b6774bc1d41d7c43e4/kiota_client_factory.go#L147)

**Comment by meain** [comment]
> It might be an ordering thing. Does it also pass with this change?

The test does pass even with the inverted order

**Comment by meain** [comment]
With some testing looks like ordering compression to be before retry and the fix in compression middleware to add seek does seem to fix my issue. I'll create a PR to add seek.

**Comment by baywet** [comment]
Thank you for the additional information.

Quick follow-up about the order: in your application were you leveraging the default factory for middleware? or building your set of middleware handlers manually? (I'm trying to understand whether we need to change the order in the factory to avoid multiple compressions during retrials)

**Comment by meain** [comment]
Oh, we were creating a custom set of middlewares, but looks like the [builtin one](https://github.com/meain/kiota-http-go/blob/856d46e33b83776f95916767a81648339d3f1663/kiota_client_factory.go#L118) creates a list out of a map which might have the same ish troubles.

**Comment by baywet** [comment]
Thank you for the additional information.
And there's no real fix around that because maps in go do not preserve insertion orders. (unless we ditch the map all together).
