### ISSUE TITLE
Is there some way to globally override default 100s timeout

### ISSUE THREAD

**Issue by meain** [microsoft/kiota-http-go#70]
From https://github.com/microsoftgraph/msgraph-sdk-go/issues/302#issuecomment-1282421659 and https://github.com/microsoft/kiota-http-go/pull/24 , looks like the library by default adds a 100s timeout if none is present. I understand that we can pass a context with a Deadline, but this becomes a problem when we have to do this for all requests. I was hoping to use the `Timeout` in [http client](https://github.com/microsoft/kiota-http-go/blob/c10a3abe41bfc4f46471b39a25cb58f3596c4662/kiota_client_factory.go#L73) instead of a context deadline. Is there some way to globally override this 100s timeout?

Other references:
- https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/6
- https://github.com/microsoft/kiota-http-go/pull/24

**Comment by rkodev** [comment]
Hi @meain, thanks for your interest in the SDK. We currently don't have a way to define a global deadline, a PR is however out that should be able to address your request https://github.com/microsoft/kiota-http-go/pull/71

**Comment by meain** [comment]
Awesome, thanks @rkodev.

**Comment by meain** [comment]
Thanks for the quick fix, but there is one more item that I would like to address which is regarding setting empty timeout. Is there some way to avoid setting a timeout. We were using `0` value for `http.Timeout` for downloading large files so as to ensure that it would not timeout (until the server decides to), but I don't think that would be possible here anymore.
