### ISSUE TITLE
Redirect handler fails when getting drive items using Graph sdk

### ISSUE THREAD

**Issue by eric-millin** [microsoft/kiota-http-go#97]
See https://github.com/microsoftgraph/msgraph-sdk-go/issues/485

I'm trying to get the contents of a drive item. When I use the SDK client to make the call, I get a 400. However, when I curl the same URL, it works.

### Details

Here's roughly what happens:
1. Client calls `https://graph.microsoft.com/v1.0/drives/<drive-id>/items/<item-id>/content`.
   ```go
   graphClient.DrivesById(driveId).ItemsById(itemId).Content().Get(ctx, nil)
   ```
3. API returns `302` to `https://mytech.sharepoint.com/_layouts/15/download.aspx?UniqueId=ugly-gu-id&Translate=false&tempauth=some.jwt.token&ApiVersion=2.0`
4. After client redirects, the API returns `400` with the message
   > \<h2>Our services aren't available right now\</h2>\<p>We're working to restore all services as soon as possible. Please check back soon.\</p>0123

However, If I curl the redirect URL, e.g. 
   ```shell
   curl "https://mytech.sharepoint.com/_layouts/15/download.aspx?UniqueId=ugly-gu-id&Translate=false&tempauth=some.jwt.token&ApiVersion=2.0" > my.docx
   ```
the API returns a valid file.

Someone in the original thread suggested that the problem is here: 

> The fix should probably go here:
> https://github.com/microsoft/kiota-http-go/blob/53e6b699af82a23d2cac857f9d4e699e9362cc46/redirect_handler.go#L158
> 
> The URL's host is checked in order to drop the Authorization header if it's different, but the Host: header is never updated.

**Comment by baywet** [comment]
Thanks @eric-millin for reporting this.
Is this something you'd be willing to submit a pull request for?

**Comment by eric-millin** [comment]
@baywet. Theoretically. I looked at it with a PR in mind, but wasn't sure if the unupdated `Host` header is indeed the bug. I haven't been working with SDK recently so haven't had a chance to play with it.

**Comment by eric-millin** [comment]
Closing at request of @rkodev
